apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-system

resources:
- ../../apiserver/deploy/base
- ../../ray-operator/config/rbac
- ../../ray-operator/config/manager

images:
- name: kuberay/apiserver
  newName: quay.io/kuberay/apiserver
  newTag: nightly
- name: kuberay/operator
  newName: quay.io/kuberay/operator
  newTag: nightly

