{{- if .Values.rbacEnable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "ray-operator-ant.labels" . | indent 4 }}
  name: {{ include "ray-operator-ant.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  - daemonsets
  - replicasets
  - statefulsets
  - statefulsets/status
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.ray.alipay.com
  resources:
  - rayclusters
  - rayclusterv2s
  - rayclusterv2s/status
  verbs:
  - "*"
- apiGroups:
  - ops.ray.alipay.com
  resources:
  - podpools
  - podpools/status
  verbs:
  - "*"
- apiGroups:
    - ops.ray.alipay.com
  resources:
    - podautoscalers
  verbs:
    - "*"
{{- end }}
