- label: Buildkite example
  instance_size: large
  image: golang:1.17
  commands:
    - ls -alp /workdir
    - export PATH=$PATH:/usr/local/go/bin
    - cd /workdir/ray-operator
    - make test

- label: KinD in Docker
  instance_size: large
  image: golang:1.17
  commands:
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind
    - kind create cluster