- label: kind and kubectl
  instance_size: large
  image: golang:1.17
  commands:
    # Install Go
    - export PATH=$PATH:/usr/local/go/bin

    # Install kind
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind

    # Install Docker
    - bash scripts/install-docker.sh

    # Delete dangling clusters
    - kind delete clusters --all

    # Install kubectl.
    - curl -LO https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
    - curl -LO "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl.sha256"
    - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    # Create the cluster
    - time kind create cluster --wait 120s --config tests/framework/config/kind-config-buildkite.yml
    - docker ps

    # Now the kind node is running, it exposes port 6443 in the dind-daemon network.
    - kubectl config set clusters.kind-kind.server https://docker:6443

    # Verify that kubectl works
    - kubectl version
    - kubectl cluster-info
    - kubectl get nodes
    - kubectl get pods --all-namespaces
