- label: 'Test E2E (kubectl-plugin)'
  instance_size: large
  image: golang:1.22
  commands:
    - source .buildkite/setup-env.sh
    - kind create cluster --wait 900s --config ./tests/framework/config/kind-config-buildkite.yml
    - kubectl config set clusters.kind-kind.server https://docker:6443
    # Build nightly KubeRay operator image
    - pushd ray-operator
    - IMG=kuberay/operator:nightly make docker-image
    - kind load docker-image kuberay/operator:nightly
    - IMG=kuberay/operator:nightly make deploy
    - kubectl wait --timeout=90s --for=condition=Available=true deployment kuberay-operator
    - popd && pushd kubectl-plugin
    # Setup gotestfmt
    - go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
    - set -euo pipefail
    - export PATH=$PATH:$(go env GOPATH)/bin
    # Run e2e tests and pipe output to gotestfmt
    - KUBERAY_TEST_TIMEOUT_SHORT=1m KUBERAY_TEST_TIMEOUT_MEDIUM=5m KUBERAY_TEST_TIMEOUT_LONG=10m go test -timeout 60m -v ./test/e2e -json 2>&1 | gotestfmt
