- label: 'Test Artifacts'
  instance_size: large
  image: golang:1.22
  commands:
    - source .buildkite/setup-env.sh
    - kind create cluster --wait 900s --config ./tests/framework/config/kind-config-buildkite.yml
    - kubectl config set clusters.kind-kind.server https://docker:6443
    - echo "hello" > /artifact-mount/hello.txt
