- label: Second pipeline
  commands:
    - cd /workdir/ray-operator
    - echo Second command
    - bash install_docker.sh
    - docker ps
    - bash build.sh custom_image
    - docker run -t --rm custom_image cat /tmp/yeah
  instance_size: small 
  image: ubuntu:focal