apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-head-monitor
  namespace: prometheus-system
  labels:
    release: prometheus-operator
    ray.io/node-type: head
spec:
  jobLabel: ray-head
  namespaceSelector:
    matchNames:
      - default
      - ray-system
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
    - port: metrics
  targetLabels:
  - ray.io/cluster

