apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-simple
spec:
  rayVersion: '1.3.0'
  headNodeSpec:
    serviceType: "NodePort"
    params:
      port: '6379'
      object-manager-port: '12345'
      node-manager-port: '12346'
      object-store-memory: '100000000'
      redis-password: 'AwesomeRay'
      dashboard-host: '0.0.0.0'
      num-cpus: '1'
      node-ip-address: $MY_POD_IP # auto-completed as the head pod IP
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:1.3.0
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 6379
