apiVersion: v1
kind: ResourceQuota
metadata:
  name: ray-quota
spec:
  hard:
    cpu: "4000"
    memory: 20Gi
    pods: "5"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["ray-priority"]