apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-system

resources:
- namespace.yaml
- ../base
- ../../ray-operator/config/manager/namespace-scope
- ../../ray-operator/config/rbac/namespace-scope

configurations:
- params.yaml

images:
  - name: kuberay/apiserver
    newName: kuberay/apiserver
    newTag: nightly
  - name: kuberay/operator
    newName: kuberay/operator
    newTag: nightly
