kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        # enable auditing flags on the API server
        extraArgs:
          audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
          audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
        # mount new files / directories on the control plane
        extraVolumes:
          - name: audit-policies
            hostPath: /etc/kubernetes/policies
            mountPath: /etc/kubernetes/policies
            readOnly: true
            pathType: "DirectoryOrCreate"
          - name: "audit-logs"
            hostPath: "/var/log/kubernetes"
            mountPath: "/var/log/kubernetes"
            readOnly: false
            pathType: DirectoryOrCreate
  # mount the local file on the control plane
  extraMounts:
    - hostPath: ray-operator/config/security/audit-policy.yaml
      containerPath: /etc/kubernetes/policies/audit-policy.yaml
      readOnly: true


  extraPortMappings:
    - containerPort: 30379
      hostPort: 6379
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 30265
      hostPort: 8265
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 30001
      hostPort: 10001
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 32365
      hostPort: 52365
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 30800
      hostPort: 8000
      listenAddress: "0.0.0.0"
      protocol: tcp
