batchScheduler:
  enabled: false
fullnameOverride: kuberay-operator
image:
  pullPolicy: IfNotPresent
  repository: kuberay/operator
  tag: nightly
livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 5
nameOverride: kuberay-operator
rbacEnable: true
readinessProbe:
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 5
resources:
  limits:
    cpu: 100m
    memory: 512Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  create: true
  name: kuberay-operator
