apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-interactive-mode
  namespace: default
spec:
  # InteractiveMode is only used in kubectl plugin
  submissionMode: InteractiveMode
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - image: rayproject/ray:2.41.0
              name: ray-head
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
    rayVersion: 2.41.0
    workerGroupSpecs:
      - groupName: default-group
        rayStartParams:
          metrics-export-port: "8080"
        replicas: 1
        template:
          spec:
            containers:
              - image: rayproject/ray:2.41.0
                name: ray-worker
                resources:
                  limits:
                    cpu: "2"
                    memory: 4Gi
                  requests:
                    cpu: "2"
                    memory: 4Gi
