apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-interactive-mode
  namespace: default
spec:
  # InteractiveMode means KubeRay doesn't submit job for you.
  # Instead, wait for user to submit job and provide the job submission ID.
  submissionMode: InteractiveMode
  # In interactive mode, the job is created externally, and the job ID is provided by the user
  jobId: "example-job-id"
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - image: rayproject/ray:2.41.0
              name: ray-head
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
    rayVersion: 2.41.0
    workerGroupSpecs:
      - groupName: default-group
        rayStartParams:
          metrics-export-port: "8080"
        replicas: 1
        template:
          spec:
            containers:
              - image: rayproject/ray:2.41.0
                name: ray-worker
                resources:
                  limits:
                    cpu: "2"
                    memory: 4Gi
                  requests:
                    cpu: "2"
                    memory: 4Gi
