# Install RoleBinding for namespaces listed in watchNamespace.
# This should be consistent with `rolebinding.yaml`, except for the `kind` field.
{{- if and .Values.rbacEnable .Values.singleNamespaceInstall }}
{{- $watchNamespaces := default .Values.watchNamespace (list .Release.Namespace) }}
{{- range $namespace := $watchNamespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{ include "kuberay-operator.labels" $ | nindent 4 }}
  name: {{ include "kuberay-operator.fullname" $ }}
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount.name  }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kuberay-operator.fullname" $ }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
