{{- if and .Values.rbacEnable (not .Values.singleNamespaceInstall) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raycluster-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  - rayclusters/status
  verbs:
  - get
  - list
  - watch
{{- end }}
