# permissions for end users to view rayjobs.
{{- if and .Values.rbacEnable (not .Values.singleNamespaceInstall) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raycluster-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  verbs:
  - create
  - update
  - delete
  - patch
  - deletecollection
{{- end }}
