apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-apiserver
  labels:
    control-plane: kuberay-apiserver
spec:
  selector:
    matchLabels:
      control-plane: kuberay-apiserver
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kuberay-apiserver
    spec:
      serviceAccountName: kuberay-apiserver
      containers:
      - name: kuberay-apiserver-container
        image: kuberay/apiserver
        ports:
        - containerPort: 8888
        - containerPort: 8887
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kuberay-apiserver-service
  labels:
    control-plane: kuberay-apiserver
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
spec:
  type: NodePort
  selector:
    control-plane: kuberay-apiserver
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 31888
    - name: rpc
      port: 8887
      targetPort: 8887
      nodePort: 31887

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: kuberay-apiserver
  name: kuberay-apiserver

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: kuberay-apiserver
  name: kuberay-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberay-apiserver
subjects:
  - kind: ServiceAccount
    name: kuberay-apiserver
    namespace: ray-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    control-plane: kuberay-apiserver
  name: kuberay-apiserver
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
