apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ray-system
resources:
- apiserver.yaml
patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
    name: kuberay-apiserver
    version: v1
commonLabels:
  app.kubernetes.io/component: kuberay-apiserver
  app.kubernetes.io/name: kuberay
images:
- name: kuberay/apiserver
  newName: kuberay/apiserver
  newTag: latest
