# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kuberay-apiserver
  name: kuberay-apiserver-metrics-monitor
  namespace: ray-system
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      control-plane: kuberay-apiserver