resources:
- manager.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: kuberay
  app.kubernetes.io/component: kuberay-operator
