resources:
- manager.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: kuberay/operator
  newName: brucezhang90/bruce-docker-repo
  newTag: health_kuberay
