apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: system
  labels:
    control-plane: kuberay-operator
spec:
  selector:
    matchLabels:
      control-plane: kuberay-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kuberay-operator
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kuberay-operator
      containers:
      - command:
        - /manager
#        args:
#        - --enable-leader-election
        image: kuberay/operator
        name: ray-manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
