apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: ray-operator
  name: ray-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-operator
  namespace: system
  labels:
    control-plane: ray-operator
spec:
  selector:
    matchLabels:
      control-plane: ray-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: ray-operator
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ray-operator-service-account
      containers:
      - command:
        - /manager
#        args:
#        - --enable-leader-election
        image: controller:latest
        name: ray-manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
