---
# Source: kuberay-operator/templates/ray_raycluster_viewer_role.yaml
# permissions for end users to view rayjobs.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raycluster-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  - rayclusters/status
  verbs:
  - get
  - list
  - watch
