---
# Source: kuberay-operator/templates/ray_rayjob_viewer_role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rayjob-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ray.io
  resources:
  - rayjobs
  - rayjobs/status
  verbs:
  - get
  - list
  - watch
