# permissions for end users to view rayclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: raycluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ray-operator
    app.kubernetes.io/part-of: ray-operator
    app.kubernetes.io/managed-by: kustomize
  name: raycluster-viewer-role
rules:
- apiGroups:
  - ray.io
  resources:
  - rayclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ray.io
  resources:
  - rayclusters/status
  verbs:
  - get
