name: Go-build-and-test

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

jobs:
  build_apiserver:
    env:
      working-directory: ./apiserver
      cli-working-directory: ./cli
    name: Build Apiserver, CLI Binaries and Docker Images
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: master

      - name: list directories
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          ls -R

      - name: install kubebuilder
        run: |
          wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
          sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

      - name: Get revision SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get dependencies
        run: go mod download
        working-directory: ${{env.working-directory}}

      - name: Build
        run: go build ./...
        working-directory: ${{env.working-directory}}

      - name: Test
        run: go test ./...
        working-directory: ${{env.working-directory}}

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Build Docker Image - Apiserver
        run: |
          docker build -t kuberay/apiserver:${{ steps.vars.outputs.sha_short }} -f apiserver/Dockerfile .
          docker save -o /tmp/apiserver.tar kuberay/apiserver:${{ steps.vars.outputs.sha_short }}

      - name: Upload Artifact Apiserver
        uses: actions/upload-artifact@v2
        with:
          name: apiserver_img
          path: /tmp/apiserver.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Apiserver to DockerHub
        run: |
          docker push kuberay/apiserver:${{ steps.vars.outputs.sha_short }};
          docker image tag kuberay/apiserver:${{ steps.vars.outputs.sha_short }} kuberay/apiserver:nightly;
          docker push kuberay/apiserver:nightly
        working-directory: ${{env.working-directory}}

      - name: Build CLI
        run: go build -o kuberay -a main.go
        working-directory: ${{env.cli-working-directory}}

  build_operator:
    env:
      working-directory: ./ray-operator
    name: Build Operator Binaries and Docker Images
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Default value should work for both pull_request and merge(push) event.
        ref: master

    - name: list directories
      working-directory: ${{env.working-directory}}
      run: |
        pwd
        ls -R

    - name: install kubebuilder
      run: |
        wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
        sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

    - name: Get revision SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Get dependencies
      run: go mod download
      working-directory: ${{env.working-directory}}

    - name: Build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: make test
      working-directory: ${{env.working-directory}}

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build Docker Image - Operator
      run: |
        IMG=kuberay/operator:${{ steps.vars.outputs.sha_short }} make docker-image
        docker save -o /tmp/operator.tar kuberay/operator:${{ steps.vars.outputs.sha_short }}
      working-directory: ${{env.working-directory}}

    - name: Upload Artifact Operator
      uses: actions/upload-artifact@v2
      with:
        name: operator_img
        path: /tmp/operator.tar

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Operator to DockerHub
      run: |
        docker push kuberay/operator:${{ steps.vars.outputs.sha_short }};
        docker image tag kuberay/operator:${{ steps.vars.outputs.sha_short }} kuberay/operator:nightly;
        docker push kuberay/operator:nightly
      working-directory: ${{env.working-directory}}

  test-compatibility-1_12_0:
    needs:
      - build_operator
      - build_apiserver
    runs-on: ubuntu-latest
    name: Compatibility Test - 1.12.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: master

      - uses: ./.github/workflows/actions/compatibility
        with:
          ray_version: 1.12.0

  test-compatibility-1_13_0:
    needs:
      - build_operator
      - build_apiserver
    runs-on: ubuntu-latest
    name: Compatibility Test - 1.13.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: master

      - uses: ./.github/workflows/actions/compatibility
        with:
          ray_version: 1.13.0

  test-compatibility-2_0_0:
    needs:
      - build_operator
      - build_apiserver
    runs-on: ubuntu-latest
    name: Compatibility Test - 2.0.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: master

      - uses: ./.github/workflows/actions/compatibility
        with:
          ray_version: 2.0.0

  test-compatibility-nightly:
    needs:
      - build_operator
      - build_apiserver
    runs-on: ubuntu-latest
    name: Compatibility Test - Nightly
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: master

      - uses: ./.github/workflows/actions/compatibility
        with:
          ray_version: nightly

  sample-yaml-config-test-2_0_0:
    needs:
      - build_operator
      - build_apiserver
    runs-on: ubuntu-latest
    name: Sample YAML Config Test - 2.0.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: master
      - uses: ./.github/workflows/actions/configuration
        with:
          ray_version: 2.0.0
