name: Lint and Test Charts

on:
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.4.1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (lint)
        working-directory: ./helm-chart/ray-cluster
        run: ct lint
        #  --chart-dirs ray-cluster, kuberay-operator, kuberay-apiserver

      - name: Run helm lint
        working-directory: ./helm-chart/ray-cluster
        run: helm lint