name: release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  release-kubectl-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: 'goreleaser'
          version: latest
          args: release --clean
          workdir: 'kubectl-plugin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
