name: Go-build-and-test

on:
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        # Use the same go version with build job
        go-version: '1.17'


  build_apiserver:
    env:
      working-directory: ./apiserver
      cli-working-directory: ./cli
    name: Build Apiserver, CLI Binaries and Docker Images
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'


  build_operator:
    env:
      working-directory: ./ray-operator
    name: Build Operator Binaries and Docker Images
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Default value should work for both pull_request and merge(push) event.
        ref: ${{github.event.pull_request.head.sha}}

    - name: list directories
      working-directory: ${{env.working-directory}}
      run: |
        pwd
        ls -R

    - name: install kubebuilder
      run: |
        wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
        sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

    - name: Get revision SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Get dependencies
      run: go mod download
      working-directory: ${{env.working-directory}}

    - name: Build
      run: make build
      working-directory: ${{env.working-directory}}

    # - name: Test
    #   run: make test
    #   working-directory: ${{env.working-directory}}

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build Docker Image - Operator
      run: |
        IMG=kuberay/operator:${{ steps.vars.outputs.sha_short }} make docker-image
        docker save -o /tmp/operator.tar kuberay/operator:${{ steps.vars.outputs.sha_short }}
      working-directory: ${{env.working-directory}}

    - name: Upload Artifact Operator
      uses: actions/upload-artifact@v2
      with:
        name: operator_img
        path: /tmp/operator.tar

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: contains(fromJson('["refs/heads/master", "refs/heads/release-0.3"]'), github.ref)

    - name: Push Operator to DockerHub
      run: |
        docker push kuberay/operator:${{ steps.vars.outputs.sha_short }};
        docker image tag kuberay/operator:${{ steps.vars.outputs.sha_short }} kuberay/operator:nightly;
        docker push kuberay/operator:nightly

      working-directory: ${{env.working-directory}}
      if: contains(fromJson('["refs/heads/master", "refs/heads/release-0.3"]'), github.ref)




 


  sample-yaml-config-test-2_3_0:
    needs:
      - build_operator
      - build_apiserver
      - lint
    runs-on: ubuntu-latest
    name: Sample YAML Config Test - 2.4.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: ${{github.event.pull_request.head.sha}}
      - uses: ./.github/workflows/actions/configuration
        with:
          ray_version: 2.4.0

