name: Go-build-and-test

on:
  push:
    branches:  
    - master
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      working-directory: ./ray-operator
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: '~1.15.1'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Default value should work for both pull_request and merge(push) event.
        ref: ${{github.event.pull_request.head.sha}}
    
    - name: list directories
      working-directory: ${{env.working-directory}}
      run: ls -R
    
    - name: install kubebuilder
      run: |
        wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
        sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

    - name: Get dependencies
      working-directory: ${{env.working-directory}}
      run: go mod download

    - name: Build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: make test
      working-directory: ${{env.working-directory}}
